var EARTH = 1;
var CLOUDS = 3;
var RAIN = 20;
var SYS_process;
var SYS_collisionManager;
var CLOUDS_WIDTH = 400;
var CLOUDS_HEIGHT = 120;
var RAIN_STACK = 10;
var EARTH_HEIGHT = 100;
var PROGRESS_BAR_WIDTH = 16;
var WINDOW_WIDTH = window.innerWidth;
var WINDOW_HEIGHT = window.innerHeight;
var container = document.getElementById('container');